
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[226] =
    {   0,
        0,    0,   92,   90,   89,    1,   55,   87,    5,   61,
       54,   88,   40,   41,   59,   58,   39,   57,   45,   60,
       84,   44,   38,   69,   63,   71,   86,   46,   47,   76,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   42,   62,   43,   56,
       89,   73,   87,   87,   81,    5,   79,   74,   51,   88,
       88,   83,   77,   64,   80,   65,   48,    0,    4,   78,
        0,   84,   66,   68,   72,   70,   67,   86,   82,   86,
        0,   52,   86,   86,   86,   86,   86,   86,   20,   86,
       86,   86,   86,   86,   86,    7,   86,   86,   86,   86,

       86,   86,   86,   86,   86,   86,   86,   53,   75,    0,
        0,    3,    3,    0,    0,    4,   85,   49,   50,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
        9,   86,   10,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,    0,    0,
        0,    2,   13,   86,   15,   16,   86,   86,   86,   86,
        8,   22,   86,   86,   24,   25,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   36,   86,   86,
       14,   17,   86,   86,   86,   86,   11,   86,   86,   27,
       86,   86,   86,   86,   86,   86,   34,   86,   86,    6,

       86,   86,   21,   23,   86,   12,   28,   29,   30,   31,
       32,   86,   86,   86,   86,   19,   86,   33,   86,   86,
       18,   26,   35,   37,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,    1,   27,   28,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   25,   39,   40,   41,   42,
       43,   44,   25,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    1,
        1,    1,    6,    1,    5,    7,    1,    1,    8,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    7,    1,    1
    } ;

static const flex_int16_t yy_base[240] =
    {   0,
        0,    0,  235,  854,  227,  854,  202,   55,    0,  196,
       50,   57,  854,  854,  186,   48,  854,   47,  854,   51,
       49,  854,  854,   53,  171,   54,   53,  854,  854,  158,
        0,   54,   55,   60,   58,   74,   83,   69,   56,   91,
       99,   94,  108,  106,  110,  113,  854,  104,  854,  854,
      175,  854,  116,    0,  166,    0,  854,  854,  854,   62,
        0,  157,  854,  854,  854,  854,  854,  151,    0,  854,
      120,   68,  112,  854,  854,  854,   95,  128,  854,    0,
      126,  854,  131,  136,  145,  146,  144,  145,  150,  157,
      162,  165,  163,  181,  184,  185,  193,  192,  197,  208,

      216,  212,  224,  228,  236,  238,  243,  854,  194,   99,
       84,  283,  287,  289,  294,    0,   74,  854,  854,  258,
      273,  274,  276,  285,  290,  293,  304,  305,  315,  307,
      323,  324,  325,  327,  335,  339,  347,  343,  346,  349,
      353,  363,  373,  369,  379,  388,  389,  387,  430,  432,
      436,  854,  402,  408,  412,  415,  418,  430,  431,  434,
      435,  438,  448,  454,  455,  458,  462,  470,  476,  477,
      477,  492,  494,  502,  503,  501,  502,  507,  508,  520,
      521,  524,  525,  528,  540,  541,  544,  547,  548,  560,
      563,  566,  578,  579,  579,  594,  595,  593,  601,  594,

      600,  607,  613,  617,  627,  620,  623,  630,  633,  637,
      640,  650,  653,  654,  666,  667,  670,  671,  683,  686,
      687,  690,  691,  703,  854,  754,  762,  770,  774,  778,
      782,  789,  797,  805,  813,  821,  829,  837,  845
    } ;

static const flex_int16_t yy_def[240] =
    {   0,
      225,    1,  225,  225,  225,  225,  225,  226,  227,  225,
      225,  228,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  229,  225,  225,  225,
      230,  229,  229,  229,   34,   34,   34,   34,   36,   34,
       34,   34,   34,   36,   34,   34,  225,  231,  225,  225,
      225,  225,  226,  232,  233,  227,  225,  225,  225,  228,
      234,  235,  225,  225,  225,  225,  225,  236,  237,  225,
      225,  225,  225,  225,  225,  225,  225,   34,  225,  230,
      231,  225,   34,   34,   34,   34,   36,   36,   36,   36,
       36,   36,   34,   34,   34,   34,   34,   36,   36,   34,

       34,   34,   34,   34,   34,   36,   36,  225,  231,  233,
      235,  238,  238,  238,  239,  237,  225,  225,  225,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   36,   36,   36,
       36,   36,   36,   34,   34,   34,   34,   36,  238,  238,
      238,  225,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       34,   34,   34,   34,   34,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   34,   34,   34,   36,   36,   36,

       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,    0,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225
    } ;

static const flex_int16_t yy_nxt[912] =
    {   0,
        4,    5,    6,    4,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   27,   39,   27,   40,
       27,   27,   27,   27,   41,   42,   43,   44,   45,   46,
       27,   27,   27,   47,   48,   49,   50,   54,   58,   61,
       55,   64,   66,   68,   61,   71,   62,   72,   69,   67,
       65,   62,   59,   70,   73,   74,   76,   77,   79,   79,
       79,   80,   80,   80,   71,   79,   72,   78,   80,   85,
       96,   88,  117,   62,   78,   78,   86,   97,   78,   84,

       89,   83,   87,   78,   55,   78,   78,   81,   81,   81,
       78,   95,   78,   90,   81,   91,   78,  119,   54,   78,
       78,   55,   93,   78,   92,   94,  108,   78,   78,   79,
      100,  101,   99,   98,  118,   78,   78,   78,  117,   78,
      102,   78,   78,  103,   78,   78,   78,  105,  225,  107,
       78,   79,  106,  113,  113,   78,   78,   78,  109,  104,
       78,  114,  114,  115,   78,   78,   62,   78,  114,  121,
       78,   55,   78,   78,   78,  123,   51,  120,   78,  125,
       82,   78,   78,   78,   78,  124,   78,   78,   78,   78,
      122,   78,   78,   75,   78,   78,   78,  126,   78,   78,

       78,   78,  127,   78,   78,  130,   78,   78,   63,  128,
       78,  129,   78,   78,   78,   78,  225,   78,   57,   79,
       78,   78,   78,   78,   52,  131,   78,   78,   51,   78,
      132,   78,  135,  134,  225,   78,   78,   78,   78,  133,
      225,  140,   78,  136,   78,   78,  225,   78,   78,  225,
      137,  138,   78,   78,   78,  225,  141,   78,   78,  225,
       78,  142,  225,  225,   78,   78,   78,  225,  139,  225,
       78,  143,   78,  144,  225,  146,  225,  147,   78,   78,
      148,  145,   78,  225,   78,  149,  149,   78,   78,  149,
      149,  149,  149,   78,   78,  115,  151,  151,  225,  115,

      153,  115,  154,   78,  225,   78,  115,  155,  225,   78,
       78,  152,   78,  225,   78,   78,   78,  225,   78,  159,
      156,   78,   78,  160,  225,  225,   78,   78,  225,   78,
      157,  158,   78,   78,   78,   78,  164,  161,  225,  225,
       78,   78,  225,   78,   78,  162,   78,   78,  163,   78,
      225,   78,   78,   78,   78,  225,   78,   78,  225,   78,
       78,   78,  166,   78,   78,   78,  165,   78,   78,   78,
      225,   78,  167,  225,  225,   78,   78,   78,  225,  171,
      225,   78,   78,   78,  170,   78,  168,   78,   78,   78,
       78,  169,   78,   78,   78,  172,   78,  225,   78,   78,

      173,  225,   78,   78,   78,   78,  175,  225,   78,  174,
      225,  176,   78,   78,   78,   78,  177,   78,  179,  225,
      178,   78,  225,   78,   78,   78,  180,  225,   78,  225,
       78,   78,  149,  149,  149,  149,  225,   78,  149,  149,
      225,   78,  115,   78,  115,  225,  181,   78,  115,   78,
      225,   78,   78,   78,   78,  225,   78,   78,   78,   78,
      225,  225,   78,  225,  182,   78,  225,  183,   78,   78,
       78,   78,   78,  185,   78,   78,   78,   78,  184,   78,
       78,   78,  225,  225,   78,   78,  225,   78,   78,   78,
      225,  225,  186,   78,   78,   78,   78,   78,   78,   78,

      187,   78,  225,   78,   78,   78,   78,  188,   78,   78,
      191,   78,   78,   78,  189,   78,   78,   78,   78,  192,
       78,   78,  190,   78,  225,  194,   78,   78,   78,  193,
       78,   78,   78,  195,   78,  196,   78,  198,   78,   78,
       78,   78,  197,   78,   78,   78,   78,   78,   78,   78,
      225,   78,   78,  200,  199,  225,  225,   78,   78,   78,
       78,   78,   78,   78,   78,   78,  201,  202,  225,   78,
       78,   78,  225,  203,   78,   78,  225,  225,   78,   78,
       78,   78,  204,   78,  225,   78,   78,   78,   78,  206,
       78,   78,  225,  205,   78,  207,  225,   78,   78,   78,

      208,   78,   78,  225,   78,   78,  225,   78,   78,  209,
       78,  225,  225,   78,  225,  211,   78,   78,   78,   78,
       78,   78,  225,   78,   78,  210,  225,  212,   78,   78,
       78,   78,   78,   78,  213,   78,   78,   78,  214,   78,
       78,   78,   78,   78,   78,  225,   78,  215,   78,  225,
       78,   78,   78,  216,   78,  225,   78,   78,   78,   78,
      217,   78,   78,   78,   78,  225,   78,   78,   78,   78,
       78,   78,   78,   78,   78,  225,   78,   78,   78,   78,
       78,   78,  225,   78,  218,  225,  219,   78,  225,   78,
       78,   78,   78,  220,   78,   78,  225,  225,  225,  221,

       78,  225,  225,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,  225,  222,  223,   78,   78,  225,  224,
       78,   78,   78,  225,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,  225,  225,   78,   78,  225,  225,
       78,   78,   78,  225,   78,  225,  225,  225,  225,  225,
      225,  225,  225,   78,   53,   53,   53,   53,   53,   53,
       53,   53,   56,  225,   56,   56,   56,   56,   56,   56,
       60,   60,   60,   60,   60,   60,   60,   60,   78,  225,
       78,   78,   80,  225,  225,   80,   81,   81,   81,   54,
       54,  225,   54,   54,   54,   54,   54,  110,  225,  110,

      110,  110,  110,  110,  110,   61,   61,   61,  225,   61,
       61,   61,   61,  111,  225,  111,  111,  111,  111,  111,
      111,  112,  112,  112,  112,  112,  112,  112,  112,  116,
      225,  116,  116,  116,  116,  116,  116,  114,  114,  114,
      114,  114,  114,  114,  114,  150,  150,  150,  150,  150,
      150,  150,  150,    3,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,

      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225
    } ;

static const flex_int16_t yy_chk[912] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,   11,   12,
        8,   16,   18,   20,   60,   21,   12,   21,   20,   18,
       16,   60,   11,   20,   24,   24,   26,   26,   27,   32,
       33,   27,   32,   33,   72,   34,   72,   35,   34,   34,
       39,   35,  117,  111,   35,   39,   34,   39,   38,   33,

       35,   32,   34,   36,  110,   38,   39,   27,   32,   33,
       36,   38,   37,   36,   34,   36,   36,   77,   53,   37,
       40,   53,   37,   42,   36,   37,   48,   40,   41,   48,
       42,   42,   41,   40,   73,   41,   42,   43,   71,   45,
       42,   41,   46,   42,   43,   44,   45,   44,   81,   46,
       43,   81,   45,   68,   68,   46,   44,   78,   48,   43,
       83,   68,   68,   68,   78,   84,   62,   83,   68,   84,
       78,   55,   84,   83,   85,   86,   51,   83,   84,   88,
       30,   85,   86,   87,   88,   87,   88,   85,   86,   89,
       85,   89,   93,   25,   87,   88,   90,   89,   90,   93,

       89,   91,   90,   91,   92,   93,   92,   90,   15,   91,
       94,   92,   91,   95,   96,   92,  109,   94,   10,  109,
       95,   96,   97,   94,    7,   94,   95,   96,    5,   97,
       95,   98,   99,   98,    3,   97,   99,  100,   99,   97,
        0,  102,   98,   99,  100,  101,    0,   99,  102,    0,
      100,  101,  101,  103,  102,    0,  102,  104,  101,    0,
      103,  103,    0,    0,  104,  105,  103,    0,  101,    0,
      104,  104,  105,  105,    0,  106,    0,  106,  105,  106,
      107,  105,  107,    0,  107,  112,  112,  120,  106,  113,
      113,  114,  114,  107,  120,  112,  115,  115,    0,  113,

      120,  114,  121,  122,    0,  123,  115,  122,    0,  121,
      122,  115,  123,    0,  124,  121,  122,    0,  123,  125,
      123,  124,  126,  126,    0,    0,  125,  124,    0,  126,
      124,  124,  125,  127,  128,  126,  130,  127,    0,    0,
      127,  128,    0,  130,  129,  128,  127,  128,  129,  130,
        0,  129,  131,  132,  133,    0,  134,  129,    0,  131,
      132,  133,  134,  134,  135,  131,  132,  133,  136,  134,
        0,  135,  135,    0,    0,  136,  137,  135,    0,  139,
        0,  136,  138,  137,  138,  139,  136,  139,  140,  137,
      140,  137,  141,  138,  141,  140,  139,    0,  144,  140,

      141,    0,  142,  141,  142,  144,  143,    0,  145,  142,
        0,  144,  143,  142,  143,  145,  145,  146,  147,    0,
      146,  145,    0,  143,  146,  147,  148,    0,  148,    0,
      146,  147,  149,  149,  150,  150,    0,  148,  151,  151,
        0,  153,  149,  153,  150,    0,  154,  154,  151,  154,
        0,  155,  153,  155,  156,    0,  156,  157,  154,  157,
        0,    0,  155,    0,  157,  156,    0,  158,  157,  158,
      159,  158,  159,  160,  161,  160,  161,  162,  159,  162,
      158,  159,    0,    0,  160,  161,    0,  163,  162,  163,
        0,    0,  163,  164,  165,  164,  165,  166,  163,  166,

      164,  167,    0,  167,  164,  165,  171,  167,  166,  168,
      170,  168,  167,  171,  168,  169,  170,  169,  170,  171,
      168,  172,  169,  173,    0,  173,  169,  170,  172,  172,
      173,  174,  175,  174,  172,  175,  173,  177,  174,  175,
      176,  177,  176,  177,  174,  175,  178,  179,  178,  179,
        0,  176,  177,  180,  179,    0,    0,  178,  179,  180,
      181,  180,  181,  182,  183,  182,  183,  184,    0,  184,
      180,  181,    0,  185,  182,  183,    0,    0,  184,  185,
      186,  185,  186,  187,    0,  187,  188,  189,  188,  189,
      185,  186,    0,  188,  187,  191,    0,  188,  189,  190,

      192,  190,  191,    0,  191,  192,    0,  192,  195,  193,
      190,    0,    0,  191,    0,  195,  192,  193,  194,  193,
      194,  195,    0,  196,  197,  194,    0,  196,  193,  194,
      196,  197,  198,  200,  198,  200,  196,  197,  199,  201,
      199,  201,  199,  198,  200,    0,  202,  201,  202,    0,
      201,  199,  203,  202,  203,    0,  204,  202,  204,  206,
      205,  206,  207,  203,  207,    0,  205,  204,  205,  208,
      206,  208,  209,  207,  209,    0,  210,  205,  210,  211,
      208,  211,    0,  209,  212,    0,  213,  210,    0,  212,
      211,  212,  213,  214,  213,  214,    0,    0,    0,  215,

      212,    0,    0,  213,  214,  215,  216,  215,  216,  217,
      218,  217,  218,    0,  217,  219,  215,  216,    0,  220,
      217,  218,  219,    0,  219,  220,  221,  220,  221,  222,
      223,  222,  223,  219,    0,    0,  220,  221,    0,    0,
      222,  223,  224,    0,  224,    0,    0,    0,    0,    0,
        0,    0,    0,  224,  226,  226,  226,  226,  226,  226,
      226,  226,  227,    0,  227,  227,  227,  227,  227,  227,
      228,  228,  228,  228,  228,  228,  228,  228,  229,    0,
      229,  229,  230,    0,    0,  230,  231,  231,  231,  232,
      232,    0,  232,  232,  232,  232,  232,  233,    0,  233,

      233,  233,  233,  233,  233,  234,  234,  234,    0,  234,
      234,  234,  234,  235,    0,  235,  235,  235,  235,  235,
      235,  236,  236,  236,  236,  236,  236,  236,  236,  237,
        0,  237,  237,  237,  237,  237,  237,  238,  238,  238,
      238,  238,  238,  238,  238,  239,  239,  239,  239,  239,
      239,  239,  239,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,

      225,  225,  225,  225,  225,  225,  225,  225,  225,  225,
      225
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "icg.l"
#line 2 "icg.l"
	#include "y.tab.h"
	#include<stdio.h>
	#include<string.h>
	#include<stdlib.h>
	#include<malloc.h>

	#define CAPACITY 1000
struct symbol
{
	char key[100];
	char class[100];
	char data[100];
	char value[100];
	int nestval;
	int lineno;
	int length;
	int params_count;
}symb[CAPACITY];

struct constant
{
	char key[100];
	char data[100];
	int length;
}cons[CAPACITY];


int currnest = 0;
extern int yylval;

int hash(char *str)
{
	int value = 0;
	for(int i = 0 ; i < strlen(str) ; i++)
	{
		value = 10*value + (str[i] - 'A');
		value = value % CAPACITY;
		while(value < 0)
			value = value + CAPACITY;
	}
	return value;
}
int searchST(char *str)
{
	int value = hash(str);
	if(symb[value].length == 0)
		return 0;
	else if(strcmp(symb[value].key,str)==0)
		return value;
	else
	{
		for(int i = value + 1 ; i!=value ; i = (i+1)%CAPACITY)
    	if(strcmp(symb[i].key,str)==0)
    		return 1;
    return 0;
  }
}
int searchCT(char *str)
{
	int value = hash(str);
  if(cons[value].length == 0)
		return 0;
	else if(strcmp(cons[value].key,str)==0)
		return 1;
	else
	{
		for(int i = value + 1 ; i!=value ; i = (i+1)%CAPACITY)
			if(strcmp(cons[i].key,str)==0)
				return 1;
		return 0;
	}
}
void insertSymboltype(char *str1, char *str2)
{
	for(int i = 0 ; i < (CAPACITY+1) ; i++)
	{
		if(strcmp(symb[i].key,str1)==0)
		{
			strcpy(symb[i].data,str2);
		}
	}
	}

void insertSymbolvalue(char *str1, char *str2)
{
	for(int i = 0 ; i < (CAPACITY+1) ; i++)
	{
		if(strcmp(symb[i].key,str1)==0 && symb[i].nestval == currnest)
		{
			strcpy(symb[i].value,str2);
		}
	}
}

void insertSTnest(char *s, int nest)
{
	if(searchST(s) && symb[searchST(s)].nestval != 99999)
	{
		int pos = 0;
		int value = hash(s);
		for (int i = value + 1 ; i!=value ; i = (i+1)%(CAPACITY+1))
		{
			if(symb[i].length == 0)
			{
				pos = i;
				break;
			}
		}

		strcpy(symb[pos].key,s);
		strcpy(symb[pos].class,"Identifier");
		symb[pos].length = strlen(s);
		symb[pos].nestval = nest;
		symb[pos].params_count = -1;
		symb[pos].lineno = yylineno;
	}
	else
	{
		for(int i = 0 ; i < (CAPACITY+1) ; i++)
		{
			if(strcmp(symb[i].key,s)==0 )
			{
				symb[i].nestval = nest;
			}
		}
	}
}

void insertSTparamscount(char *s, int count)
{
	for(int i = 0 ; i < (CAPACITY+1) ; i++)
	{
		if(strcmp(symb[i].key,s)==0 )
		{
			symb[i].params_count = count;
		}
	}
}

int getSTparamscount(char *s)
{
	for(int i = 0 ; i < (CAPACITY+1) ; i++)
	{
		if(strcmp(symb[i].key,s)==0 )
		{
			return symb[i].params_count;
		}
	}
	return -1;
}

void insertSTF(char *s)
{
	for(int i = 0 ; i < (CAPACITY+1) ; i++)
	{
		if(strcmp(symb[i].key,s)==0 )
		{
			strcpy(symb[i].class,"Function");
			return;
		}
	}

}

void insertSymbolline(char *str1, int line)
{
	for(int i = 0 ; i < (CAPACITY+1) ; i++)
	{
		if(strcmp(symb[i].key,str1)==0)
		{
			symb[i].lineno = line;
		}
	}
}


void insertsymbol(char *str1, char *str2)
{
	if(searchST(str1))
	{

		if(strcmp(symb[searchST(str1)].class,"Identifier")==0 && strcmp(str2,"Array Identifier")==0)
		{
			printf("Error use of array\n");
			exit(0);
		}
		return;
	}
	else
	{
		int value = hash(str1);
		if(symb[value].length == 0)
		{
			strcpy(symb[value].key,str1);
			strcpy(symb[value].class,str2);
			symb[value].length = strlen(str1);
			symb[value].nestval = 99999;
			symb[value].params_count = -1;
			insertSymbolline(str1,yylineno);
			return;
		}

		int pos = 0;

		for (int i = value + 1 ; i!=value ; i = (i+1)%CAPACITY)
			if(symb[i].length == 0)
			{
				pos = i;
				break;
			}

		strcpy(symb[pos].key,str1);
		strcpy(symb[pos].class,str2);
		symb[pos].length = strlen(str1);
		symb[pos].nestval = 99999;
		symb[pos].params_count = -1;
	}
}

void insertconstant(char *str1, char *str2)
{
	if(searchCT(str1))
		return;
	else
	{
		int value = hash(str1);
		if(cons[value].length == 0)
		{
			strcpy(cons[value].key,str1);
			strcpy(cons[value].data,str2);
			cons[value].length = strlen(str1);
			return;
		}

		int pos = 0;

		for (int i = value + 1 ; i!=value ; i = (i+1)%CAPACITY)
			if(cons[i].length == 0)
			{
				pos = i;
				break;
			}

		strcpy(cons[pos].key,str1);
		strcpy(cons[pos].data,str2);
		cons[pos].length = strlen(str1);
	}
}

void deletedata (int nesting)
{
	for(int i = 0 ; i < (CAPACITY+1) ; i++)
	{
		if(symb[i].nestval == nesting)
			symb[i].nestval = 99999;
	}
}

int checkscope(char *s)
{
	int flag = 0;
	for(int i = 0 ; i < CAPACITY ; i++)
	{
		if(strcmp(symb[i].key,s)==0)
		{
			if(symb[i].nestval > currnest)
				flag = 1;
			else
			{
				flag = 0;
				break;
			}
		}
	}
	if(!flag)
	{
		return 1;
	}
	else
	{
		return 0;
	}
}

int check_id_is_func(char *s)
{
	for(int i = 0 ; i < CAPACITY ; i++)
	{
		if(strcmp(symb[i].key,s)==0)
		{
			if(strcmp(symb[i].class,"Function")==0)
				return 1;
		}
	}
	return 0;
}

int checkarray(char *s)
{
	for(int i = 0 ; i < CAPACITY ; i++)
	{
		if(strcmp(symb[i].key,s)==0)
		{
			if(strcmp(symb[i].class,"Array Identifier")==0)
			{
				return 0;
			}
		}
	}
	return 1;
}

int duplicate(char *s)
{
	for(int i = 0 ; i < CAPACITY ; i++)
	{
		if(strcmp(symb[i].key,s)==0)
		{
			if(symb[i].nestval == currnest)
			{
        return 1;
			}
		}
	}

	return 0;
}

int check_duplicate(char* str)
{
	for(int i=0; i<(CAPACITY+1); i++)
	{
		if(strcmp(symb[i].key, str) == 0 && strcmp(symb[i].class, "Function") == 0)
		{
			printf("Function redeclaration not allowed\n");
			exit(0);
		}
	}
}

int check_declaration(char* str, char *check_type)
{
	for(int i=0; i<(CAPACITY+1); i++)
	{
		if(strcmp(symb[i].key, str) == 0 && strcmp(symb[i].class, "Function") == 0 || strcmp(symb[i].key,"printf")==0 )
		{
			return 1;
		}
	}
	return 0;
}

int check_params(char* type_specifier)
{
	if(!strcmp(type_specifier, "void"))
	{
		printf("Parameters cannot be of type void\n");
		exit(0);
	}
	return 0;
}

char gettype(char *s, int flag)
{
	for(int i = 0 ; i < (CAPACITY+1) ; i++ )
	{
		if(strcmp(symb[i].key,s)==0)
		{
			return symb[i].data[0];
		}
	}

}

void printsymbol()
{
  printf("\n\n*****SYMBOL TABLE*****\n\n");
	printf("Class\t\t\tType\t\t\tName\t\t\tValue\t\t\tLineNo\t\t\tNesting\t\t\tParams Count\n\n");
	for(int i = 0 ; i < CAPACITY ; i++)
	{
		if(symb[i].length == 0)
			continue;

		printf("%-24s%-24s%-24s%-24s%-24d%-24d%-24d\n", symb[i].data,symb[i].class,symb[i].key,symb[i].value,symb[i].lineno,	symb[i].nestval, symb[i].params_count );
	}
}



void printconstant()
{
  printf("\n\n*****CONSTANT TABLE*****\n\n");
	printf("Type\t\t\t\tValue\n\n");
	for(int i = 0 ; i < CAPACITY ; i++)
	{
		if(cons[i].length == 0)
			continue;
		printf("%-32s%-32s\n", cons[i].data,cons[i].key);
	}
}
char CID[20];
char CTYPE[20];
char CVAL[20];



#line 1127 "lex.yy.c"
#line 1128 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 415 "icg.l"


#line 1348 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 226 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 854 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 417 "icg.l"
{yylineno++;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 418 "icg.l"
{} ;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 419 "icg.l"
{del();}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 420 "icg.l"
{};
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 421 "icg.l"
{};
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 422 "icg.l"
{return WHILE;  insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 423 "icg.l"
{  insertsymbol(yytext, "Keyword"); return IF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 424 "icg.l"
{  insertsymbol(yytext, "Keyword"); return ELSE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 425 "icg.l"
{  insertsymbol(yytext, "Keyword"); return FOR;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 426 "icg.l"
{ strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword"); return INT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 427 "icg.l"
{ strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword"); return FLOAT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 428 "icg.l"
{ insertsymbol(yytext, "Keyword"); return RETURN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 429 "icg.l"
{  insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 430 "icg.l"
{  insertsymbol(yytext, "Keyword"); return BREAK;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 431 "icg.l"
{  insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 432 "icg.l"
{strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword"); return CHAR;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 433 "icg.l"
{ strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 434 "icg.l"
{  insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 435 "icg.l"
{ insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 436 "icg.l"
{  insertsymbol(yytext, "Keyword"); return DO;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 437 "icg.l"
{strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword"); return DOUBLE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 438 "icg.l"
{  insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 439 "icg.l"
{  insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 440 "icg.l"
{ insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 441 "icg.l"
{ strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword"); return LONG;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 442 "icg.l"
{ insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 443 "icg.l"
{ strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword"); return SHORT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 444 "icg.l"
{ strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword"); return SIGNED;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 445 "icg.l"
{  insertsymbol(yytext, "Keyword"); return SIZEOF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 446 "icg.l"
{ insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 447 "icg.l"
{ strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword"); return STRUCT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 448 "icg.l"
{  insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 449 "icg.l"
{  insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 450 "icg.l"
{ strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword");return UNION;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 451 "icg.l"
{ insertsymbol(yytext, "Keyword"); return UNSIGNED;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 452 "icg.l"
{strcpy(CTYPE,yytext); insertsymbol(yytext, "Keyword"); return VOID;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 453 "icg.l"
{ insertsymbol(yytext, "Keyword");}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 454 "icg.l"
{return SEMICOLON;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 455 "icg.l"
{return COMMA;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 456 "icg.l"
{return OP;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 457 "icg.l"
{return CP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 458 "icg.l"
{return OB;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 459 "icg.l"
{return CB;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 460 "icg.l"
{return COLON;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 461 "icg.l"
{return FULLSTOP;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 462 "icg.l"
{return OSB;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 463 "icg.l"
{return CSB;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 465 "icg.l"
{return SUBA;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 466 "icg.l"
{return LSHIFT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 467 "icg.l"
{return RSHIFT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 468 "icg.l"
{return ANDA;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 469 "icg.l"
{return XORA;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 470 "icg.l"
{return ORA;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 471 "icg.l"
{return SAND;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 472 "icg.l"
{return EXC;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 473 "icg.l"
{return QUO;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 474 "icg.l"
{return SUB;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 475 "icg.l"
{return ADD;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 476 "icg.l"
{return MUL;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 477 "icg.l"
{return DIV;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 478 "icg.l"
{return MOD;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 479 "icg.l"
{return PIPE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 480 "icg.l"
{return ASS;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 481 "icg.l"
{return INCRI;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 482 "icg.l"
{return DECRI;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 483 "icg.l"
{return LEFTSHIFT;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 484 "icg.l"
{return RIGHTSHIFT;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 485 "icg.l"
{return LESSTHANA;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 486 "icg.l"
{return LESSTHAN;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 487 "icg.l"
{return GRETHANA;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 488 "icg.l"
{return GRETHAN;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 489 "icg.l"
{return EQ;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 490 "icg.l"
{return NEQ;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 491 "icg.l"
{return AND;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 492 "icg.l"
{return OR;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 493 "icg.l"
{return UP;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 494 "icg.l"
{return MULA;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 495 "icg.l"
{return DIVA;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 496 "icg.l"
{return MODA;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 497 "icg.l"
{return ADDA;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 499 "icg.l"
{strcpy(CVAL,yytext); insertconstant(yytext,"String Constant"); return STRING;}
	YY_BREAK
case 82:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 500 "icg.l"
{strcpy(CID,yytext); insertsymbol(yytext, "Array Identifier"); return ARRAYIDEN;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 501 "icg.l"
{strcpy(CVAL,yytext); insertconstant(yytext,"Character Constant"); return CHARACTER;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 502 "icg.l"
{strcpy(CVAL,yytext); insertconstant(yytext, "Number Constant"); return INTEGER;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 503 "icg.l"
{strcpy(CVAL,yytext); insertconstant(yytext, "Floating Constant"); return FLOATC;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 504 "icg.l"
{strcpy(CID,yytext);insertsymbol(yytext,"Identifier");  return IDEN;}
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 506 "icg.l"
{del1();}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 507 "icg.l"
{del1();}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 508 "icg.l"
{};
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 509 "icg.l"
{printf("%s\n",yytext);del2();}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 512 "icg.l"
ECHO;
	YY_BREAK
#line 1868 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 226 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 226 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 225);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 512 "icg.l"


int del()
{
  printf ("\n\n\n***ERROR: INCOMPLETE MULTI LINE COMMENT***\n\n\n***PROGRAM TERMINATED***\n\n\n");
  exit(0);
}

int del1()
{
  printf ("\n\n\n***ERROR: INCOMPLETE STRING***\n\n\n***PROGRAM TERMINATED***\n\n\n");
  exit(0);
}

int del2()
{
  printf ("\n\n\n***ERROR: UNKNOWN CHARACTER***\n\n\n***PROGRAM TERMINATED***\n\n\n");
  exit(0);
}

